"""empty message

Revision ID: 234c17fafece
Revises: 7785468819b2
Create Date: 2021-04-17 05:12:14.749823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '234c17fafece'
down_revision = '7785468819b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('people_id', sa.Integer(), nullable=False))
    op.drop_column('favorites', 'peopler_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('peopler_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('favorites', 'people_id')
    # ### end Alembic commands ###
