"""empty message

Revision ID: 7785468819b2
Revises: b1090d89b917
Create Date: 2021-04-16 05:42:21.627464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7785468819b2'
down_revision = 'b1090d89b917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('image_url', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'image_url')
    # ### end Alembic commands ###
